//防止报黄条
// 单个词用全大写 多词用大驼峰

/**
 * 加载登录页*/
export const LOADING_LOGIN =  "pages/Login/Login"
/**
 * 加载主页*/
export const LOADING_INDEX =  "pages/Index/Index"
/**
 * 加载聊天详情页*/
export const LOADING_ChatDetail =  "pages/ChatDetail/ChatDetail"
/**
 * 加载搜索页*/
export const LOADING_SEARCH =  "pages/Search/SearchPage"
/**
 * 加载设置页*/
export const LOADING_SETTING =  "pages/Setting/Setting"
/**
 * 加载商品页*/
export const LOADING_SHOP =  "pages/Shop/Shop"