/**
 * 常量库
 * */
export class Constants {
  //统一色值
  /**
   * 弹窗背景色*/
  static COLOR_OpacityBlack = '#80000000'
  /**
   * 底部栏背景色*/
  static COLOR_GrayNAV = '#ff393939'
  /**
   * 侧边栏钱包背景色*/
  static COLOR_SiDerPay = 'rgba(227, 227, 227, 0.50)'

  //统一路由管理
  /**
   * 加载登录页*/
  static LOADING_LOGIN = "pages/Login/Login"
  /**
   * 加载主页*/
  static LOADING_INDEX = "pages/Index/Index"
  /**
   * 加载聊天详情页*/
  static LOADING_ChatDetail = "pages/ChatDetail/ChatDetail"
  /**
   * 加载搜索页*/
  static LOADING_SEARCH = "pages/Search/SearchPage"
  /**
   * 加载设置页*/
  static LOADING_SETTING = "pages/Setting/Setting"
  /**
   * 加载商品页*/
  static LOADING_SHOP = "pages/Shop/Shop"
  /**
   * 加载视频详情页*/
  static LOADING_VdDETAIL = "pages/My/VdDetail"
}